### ISSUE TITLE
aws link does not work for machine learning engineer nanodgree

### ISSUE THREAD

**Issue by stopachka** [udacity/dog-project#10]
when click the aws instructions

https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/53b2a19e-4e29-4ae7-aaf2-33d195dbdeba/lessons/2df3b94c-4f09-476a-8397-e8841b147f84/project

i get an error, saying i don't have access to that nanodegree

![image](https://user-images.githubusercontent.com/984574/29499156-8c08aeca-85bf-11e7-8dbc-38313e32aee0.png)

But i am in the ml engineer nanodgree, where this project is included

![image](https://user-images.githubusercontent.com/984574/29499158-94223d7e-85bf-11e7-82b1-c05049124ca9.png)

am assuming this link may be going to another nanodgree

**Comment by alexisbcook** [comment]
Thanks! Fixed.
