### ISSUE TITLE
Tensorflow-gpu 1.1.0 and python3.6 ?

### ISSUE THREAD

**Issue by hjwk** [udacity/dog-project#12]
Trying to execute pip install tensorflow-gpu==1.1.0 fails because this version simply does not exist for python 3.6. 

Should we use python 3.5 or a newer version of tensorflow-gpu ?

**Comment by alexisbcook** [comment]
Thanks!  Please use python 3.5.  I've amended the instructions.

**Comment by hjwk** [comment]
Thanks for tidying that up :)
