### ISSUE TITLE
tensor size for the dog breed classifier

### ISSUE THREAD

**Issue by chaimpollak** [udacity/dog-project#2]
The [sample model](https://raw.githubusercontent.com/udacity/dog-project/ba685d06ec965158cf0d5f1748b7f19d34b206e0/images/sample_cnn.png) has the input size of 223 * 223 while the actual tensor size is 224 * 224.

**Comment by alexisbcook** [comment]
The sample model has **output** shape (batch_size, 223, 223, 6).
