### ISSUE TITLE
List of dog names ordered wrong

### ISSUE THREAD

**Issue by fwulff** [udacity/dog-project#4]
# load list of dog names
dog_names = [item[20:-1] for item in glob("dogImages/train/*/")]

needs to use sorted(glob()) for alphabetical order, otherwise the names of dog breeds are wrong, even when the correct class is predicted

# load list of dog names
dog_names = [item[20:-1] for item in sorted(glob("dogImages/train/*/"))]

**Comment by alexisbcook** [comment]
Perfect, thanks - I've made the change. (They were already sorted on my filesystem, but it's likely not the case for all - so thanks for finding it!)
