### ISSUE TITLE
keras not working

### ISSUE THREAD

**Issue by mitranos** [udacity/dog-project#5]
The following commit 857ea11cb6182d9df87e4bcdbf8ef7f43ea7636f broke the creation of the conda environment with jupyter and keras. I believe there are some dependency issue. Keras is installed correctly on the environment but when you try to import keras in the notebook it say that could not find the module.

I have solved the issue using the previous aind-dog-mac.yml file to create the conda environment.

**Comment by alexisbcook** [comment]
Thanks! should be fixed with the most recent commit.
